name = "Crystal"
uuid = "3c6eccdf-2a89-4c24-a1d4-ff210daa8476"
authors = ["eschmidt42 <11818904+eschmidt42@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Molly = "aa0f7f06-fcc0-5ec4-a7f3-a573f33f9c4c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"